### ISSUE TITLE
Installing with JSPM throws errors. 

### ISSUE THREAD

**Issue by shaunluttin** [SpoonX/aurelia-authentication#124]
```
ProjectRoot> jspm install aurelia-authentication
     Updating registry cache...
     Looking up npm:aurelia-authentication
     Downloading npm:aurelia-authentication@2.1.1

warn Error on processPackageConfig
     Package.json dependency aurelia-dependency-injection set to npm:aurelia-dependency-injection@^1.0.0-beta.1.2.0, which is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for npm:aurelia-authentication.
         at ProjectRoot\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (ProjectRoot\node_modules\rsvp\dist\rsvp.js:245:13)
         at null._onTimeout (ProjectRoot\node_modules\rsvp\dist\rsvp.js:568:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error processing package config for npm:aurelia-authentication.

warn Installation changes not saved.
```

**Comment by doktordirk** [comment]
yeah, sorry. that's from the very soon to come install instructions. 

meanwhile use

jspm i github:spoonx/aurelia-api
jspm i github:spoonx/aurelia-authentication

or for sneak peak of the comming

jspm i aurelia-api=github:spoonx/aurelia-api@dev
jspm i aurelia-authentication=github:spoonx/aurelia-authentication@dev

**Comment by shaunluttin** [comment]
Thank you.

**Comment by doktordirk** [comment]
@shaunluttin 
you can use `jspm i aurelia-api aurelia-authentication` now to install prefixless 3.0.0-rc1
