### ISSUE TITLE
Cannot readily install lib into Aurelia

### ISSUE THREAD

**Issue by mookid8000** [SpoonX/aurelia-authentication#219]
Hello there, JavaScript n00b here... sorry if this is totally crazy, but I was expecting to be able to

```
au new --here
```

with Aurelia CLI (0.17.0) with standard options all the way, and then

```
npm install aurelia-authentication --save
```

which nicely resolves to the current latest `3.0.0-rc5`.

Now I add `aurelia-authentication` to the `dependencies` element in `aurelia.json` and then I

```
au build
```

which results in the following error:

```
Starting 'readProjectConfiguration'...
(...)
Tracing aurelia-authentication...
{ uid: 8,
  name: 'writeBundles',
  branch: false,
  error:
   { Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/extend.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/file-system.js:38:13)
       at amodroTrace.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.Module.load (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.Module.fetch (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.Module.check (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/mhg/Projects/AuNew/src/extend.js',
     moduleTree: [ 'aurelia-authentication' ],
     fileName: '/Users/mhg/Projects/AuNew/node_modules/aurelia-authentication/dist/amd/aurelia-authentication.js' },
  duration: [ 0, 177231957 ],
  time: 1469978815084 }
{ uid: 0,
  name: '<series>',
  branch: true,
  error:
   { Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/extend.js'
       at Error (native)
       at Object.fs.openSync (fs.js:640:18)
       at Object.fs.readFileSync (fs.js:508:33)
       at Object.exports.readFileSync (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/file-system.js:38:13)
       at amodroTrace.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
       at Object.context.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
       at Object.context.load (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
       at Object.Module.load (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
       at Object.Module.fetch (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
       at Object.Module.check (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
     errno: -2,
     code: 'ENOENT',
     syscall: 'open',
     path: '/Users/mhg/Projects/AuNew/src/extend.js',
     moduleTree: [ 'aurelia-authentication' ],
     fileName: '/Users/mhg/Projects/AuNew/node_modules/aurelia-authentication/dist/amd/aurelia-authentication.js' },
  duration: [ 0, 373788815 ],
  time: 1469978815097 }
{ Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/extend.js'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.exports.readFileSync (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/file-system.js:38:13)
    at amodroTrace.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/bundled-source.js:83:31)
    at Object.context.fileRead (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:176:18)
    at Object.context.load (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:357:30)
    at Object.Module.load (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:832:29)
    at Object.Module.fetch (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:822:66)
    at Object.Module.check (eval at <anonymous> (/Users/mhg/Projects/AuNew/node_modules/aurelia-cli/lib/build/amodro-trace/lib/loader/Loader.js:14:9), <anonymous>:854:30)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/mhg/Projects/AuNew/src/extend.js',
  moduleTree: [ 'aurelia-authentication' ],
  fileName: '/Users/mhg/Projects/AuNew/node_modules/aurelia-authentication/dist/amd/aurelia-authentication.js' }
```

What is wrong with me? (please just tell me - I can handle it!)

**Comment by doktordirk** [comment]
https://github.com/SpoonX/aurelia-authentication#aureli-cli

**Comment by mookid8000** [comment]
Thanks for the super-quick response! 👍  😄 

I did what it said, and then I got this:

```
{ Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/aurelia-fetch-client.js'
```

and then I ran

```
npm install aurelia-fetch-client --save
```

and added `aurelia-fetch-client` to `aurelia.json`, but then I got

```
{ Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/aurelia-api.js'
```

and then I did the same thing with `aurelia-api`, but then the same thing happened for `qs`, and `stringify`... and when I added `stringify`, it kept saying

```
{ Error: ENOENT: no such file or directory, open '/Users/mhg/Projects/AuNew/src/src/stringify.js'
```

Am I doing this wrong?

**Comment by doktordirk** [comment]
nope. this is the way to go. gets easier later, since then you know begorehand what to install

npm install stringify qs --save

**Comment by doktordirk** [comment]
@mookid8000 well, in this version what needed is:

`npm i aurelia-api aurelia-authetication aurelia-fetch-client`

and in aurelia.json

``` js
  "extend",
 "aurelia-api",
"aurelia-fetch-client",
  {
    "name": "qs",
    "path": "../node_modules/qs/dist/",
    "main": "qs"
  },
  {
    "name": "aurelia-authentication",
    "path": "../node_modules/aurelia-authentication/dist/amd",
    "main": "aurelia-authentication"
  },
  {
    "name": "jwt-decode",
    "path": "../node_modules/jwt-decode/lib",
    "main": "index"
  },
```

**Comment by mookid8000** [comment]
Excellent - that solved it 👍

**Comment by mookid8000** [comment]
Can you explain to me real quick (or point me to information somewhere else) how to resolve the typical "ENOENT: no such file or directory" error seen above?

What is it that allows for e.g. Aurelia's own dependencies to resolve perfectly by their name only (and not requiring the name-path-main object)?

**Comment by doktordirk** [comment]
there's some explanation here on howto add packages to cli .
not all of them do. main thing prventing it is a) outdated package.json structure and b) a module consists of several files. newer aurelia plugins will have a aurelia.build entry in the package.json to remove this step. but that feature might not be in all plugins and/or enabled in aurelia cli

**Comment by doktordirk** [comment]
ups the here was missing: :smile:  https://github.com/aurelia/cli

**Comment by mookid8000** [comment]
Excellent! Thanks for the quick response and fix 😄
