### ISSUE TITLE
Retreiving AuthService via IOC container causes exceptions

### ISSUE THREAD

**Issue by Bitfiddler** [SpoonX/aurelia-authentication#334]
I am trying to do something like this in my main.ts:

	import { Aurelia } from 'aurelia-framework';
	import { AuthService } from 'aurelia-authentication';
	import 'src/helpers/exceptionHelpers'
	import config from "./auth-config";

	export function configure(aurelia: Aurelia) {
		aurelia.use
			.standardConfiguration()
			.feature('src/resources')
			.developmentLogging()
			.plugin('aurelia-dialog')
			.plugin('aurelia-api', config => {
				// Register an authentication hosts
				config.registerEndpoint('auth', 'http://cpu260:7987/auth/');
			})
			.plugin('aurelia-authentication', (baseConfig) => {
				baseConfig.configure(config);
			});

		let auth = aurelia.container.get(AuthService);

		if (auth.isAuthenticated()) {
			aurelia.start().then(x => x.setRoot('src/app'));
		} else {
			aurelia.start().then(x => x.setRoot('src/unAuthorized'));
		}
		
	}

However when the statement aurelia.container.get(AuthService) is executed I get a an exception:

Error: Error invoking AuthService. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Token not found in response
Inner Error Stack:
Error: Token not found in response
------------------------------------------------

    at Authentication.getTokenFromResponse (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:968:25)
    at Authentication.getDataFromResponse (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:907:145)
    at Authentication.setResponseObject (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:843:14)
    at AuthService.setResponseObject (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:1169:27)
    at new AuthService (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:1127:12)
    at Object.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:460:14)
    at InvocationHandler.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:413:168)
    at Container.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:677:25)
    at StrategyResolver.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:604:41)
End Inner Error Stack
------------------------------------------------

    at Authentication.getTokenFromResponse (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:968:25)
    at Authentication.getDataFromResponse (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:907:145)
    at Authentication.setResponseObject (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:843:14)
    at AuthService.setResponseObject (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:1169:27)
    at new AuthService (http://cpu260:7987/jspm_packages/npm/aurelia-authentication@3.2.0/aurelia-authentication.js:1127:12)
    at Object.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:460:14)
    at InvocationHandler.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:413:168)
    at Container.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:677:25)
    at StrategyResolver.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:604:41)
End Inner Error Stack
------------------------------------------------

    at new AggregateError (http://cpu260:7987/jspm_packages/npm/aurelia-pal@1.3.0/aurelia-pal.js:39:13)
    at Container.invoke (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:679:15)
    at StrategyResolver.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:130:37)
    at Container.get (http://cpu260:7987/jspm_packages/npm/aurelia-dependency-injection@1.3.0/aurelia-dependency-injection.js:604:41)
    at r.configure (http://cpu260:7987/src/main.js:18:38)
    at eval (http://cpu260:7987/jspm_packages/npm/aurelia-bootstrapper@2.0.1/aurelia-bootstrapper.js:145:22)

Now I see that "token not found in response" is the error, however considering I haven't logged in yet, this is what I would expect.  So how can I get the authService to play nice?

**Comment by RWOverdijk** [comment]
isAuthenticated is async. It doesn't find a token but might have found a refresh token. It's trying to get a new token. Could you check local storage if there's anything there?
