### ISSUE TITLE
Unhandled promise rejection TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by egeland** [SpoonX/aurelia-authentication#34]
Since the Aurelia team updated some packages, my `aurelia-auth` has broken, and I can't figure out if it's me doing things wrong, or if there's a bug in `aurelia-auth` or the `aurelia` code base..

Any clues would be very much appreciated!

This happens on page loading, just after loading the `nav-bar.html` (`DEBUG [templating] importing resources for http://localhost:9000/dist/nav-bar.html []`):

```
Unhandled promise rejection TypeError: Cannot read property 'filter' of undefined
    at AuthFilterValueConverter.toView (http://localhost:9000/jspm_packages/github/spoonx/aurelia-auth@master/authFilter.js:22:26)
    at ValueConverter.evaluate (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.1/aurelia-binding.js:1121:33)
    at Binding.bind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.1/aurelia-binding.js:4600:36)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2745:19)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at Controller.automate (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2712:12)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:3733:22
(anonymous function) @ es6.promise.js:151
module.exports @ _invoke.js:5queue.
(anonymous function) @ _task.js:36
run @ _task.js:23
listner @ _task.js:27
```

The `es6.promise.js` and associated stuff is all from core-js v 2.0.3, which it seems the Aurelia team is moving to..

I'm stumped, so hope you have some clues..

**Comment by egeland** [comment]
After much fiddling and updating and downgrading (jspm), the error is the same, but has moved to being reported by shim:

```
Unhandled promise rejection TypeError: Cannot read property 'filter' of undefined
    at AuthFilterValueConverter.toView (http://localhost:9000/jspm_packages/github/spoonx/aurelia-auth@0.11.5/authFilter.js:22:26)
    at ValueConverter.evaluate (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.1/aurelia-binding.js:1121:33)
    at Binding.bind (http://localhost:9000/jspm_packages/npm/aurelia-binding@1.0.0-beta.1.1.1/aurelia-binding.js:4600:36)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2745:19)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at View.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:847:24)
    at Controller.bind (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2766:19)
    at Controller.automate (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:2712:12)
    at http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.1.0/aurelia-templating.js:3733:22
(anonymous function) @ shim.js:2516
module.exports @ shim.js:766
queue.(anonymous function) @ shim.js:2784
run @ shim.js:2771
listner @ shim.js:2775
```

**Comment by egeland** [comment]
After further help in the Aurelia Gitter, it turns out to (of course) be a problem in my own code.

I needed to import the aurelia router to my `nav-bar.js`:

```
import {inject} from 'aurelia-framework';
import {Router} from 'aurelia-router';
import {AuthService} from 'aurelia-auth';

@inject(AuthService, Router)
export class NavBar {

    constructor(auth, router) {
        this.auth = auth;
        this.router = router;
    }

    get isAuthenticated() {
        return this.auth.isAuthenticated();
    }

}
```
