### ISSUE TITLE
jspm install aurelia-authentication Fails

### ISSUE THREAD

**Issue by alfkonee** [SpoonX/aurelia-authentication#81]
when installing aurelia-authentication from jspm it fails with this log

```
C:\Users\Alfred\Source\Projects\ElyfeASP4\ElyfeGh\src\Elyfe.Web> jspm install aurelia-authentication
     Updating registry cache...
     Looking up npm:aurelia-authentication
     Downloading npm:aurelia-authentication@2.1.0

warn Error on processPackageConfig
     Package.json dependency aurelia-dependency-injection set to npm:aurelia-dependency-injection@^1.0.0-beta.1.2.0, whi
ch is not a valid dependency format for npm.
     It's advisable to publish jspm-style packages to GitHub or another registry so conventions are clear.

err  Error: Error processing package config for npm:aurelia-authentication.
         at C:\Users\Alfred\Source\Projects\ElyfeASP4\ElyfeGh\src\Elyfe.Web\node_modules\jspm\node_modules\systemjs-builder\lib\builder.js:27:9
         at Object.lib$rsvp$events$$default.trigger (C:\Users\Alfred\Source\Projects\ElyfeASP4\ElyfeGh\src\Elyfe.Web\node_modules\rsvp\dist\rsvp.js:245:13)
         at null._onTimeout (C:\Users\Alfred\Source\Projects\ElyfeASP4\ElyfeGh\src\Elyfe.Web\node_modules\rsvp\dist\rsvp.js:779:47)
         at Timer.listOnTimeout (timers.js:92:15)

err  Error processing package config for npm:aurelia-authentication.
```

**Comment by doktordirk** [comment]
right, but weird. can't see any problem

**Comment by doktordirk** [comment]
found it. will be fixed with https://github.com/SpoonX/aurelia-authentication/issues/73

**Comment by doktordirk** [comment]
meanwhile install from github. that'll work still
